cusswords:
  - fuck
  - shit
  - ass
  - damn
  - dick
  - nigger
  - asshole
  - cunt
  - pussy
  - bitch
  - bitches
  - douche
  - douchebag
  - douches
warnmessage: Don't cuss!
kickmessage: You were kicked for cussing!
replace: true
replaceWith: chicken
cost: 100