name: AntiCuss
version: 1.7
main: me.compressions.anticuss.AntiCuss
author: Compressions
description: Blocks cuss words!
softdepend: [Vault]

commands:
    anticuss:
        usage: /<command>
        description: AntiCuss commands!
    clearchat:
        usage: /<command>
        description: Clears chat!
    acreload:
        usage: /<command>
        description: Reloads AntiCuss config!
    chat:
        usage: /<command>
        description: Mutes chat!

permissions:
    anticuss.reload:
        description: Permission to reload config!
        default: op
    anticuss.bypass:
        description: Permission to bypass cuss word blocking!
        default: op
    anticuss.kick:
        description: Permission to kick player!
        default: false
    anticuss.clear:
        description: Permission to clear chat!
        default: op
    anticuss.mute:
        description: Permission to mute the chat!
        default: op